import { Dish } from './types';

export const dishes: Dish[] = [
    // 25 platos de Perú
    {id: 1, name: "Ceviche", country: "Perú", description: "Pescado fresco marinado en limón con cebolla y ají."},
    {id: 2, name: "Lomo Saltado", country: "Perú", description: "Carne de res salteada con cebolla, tomate, ajas fritas y arroz."},
    {id: 3, name: "Ají de Gallina", country: "Perú", description: "Crema de ají amarillo con pollo desmenuzado, servido con papas y arroz."},
    {id: 4, name: "Anticuchos", country: "Perú", description: "Brochetas de corazón de res marinadas en ají panca."},
    {id: 5, name: "Causa Rellena", country: "Perú", description: "Puré de papa amarilla con ají, limón y relleno."},
    {id: 6, name: "Rocoto Relleno", country: "Perú", description: "Ají rocoto relleno de carne molida, queso y horneado."},
    {id: 7, name: "Papa a la Huancaína", country: "Perú", description: "Papas cocidas bañadas en crema de ají amarillo y queso."},
    {id: 8, name: "Arroz con Pollo", country: "Perú", description: "Arroz cocido en cilantro y espinaca con presas de pollo."},
    {id: 9, name: "Sudado de Pescado", country: "Perú", description: "Pescado cocido al vapor en un aderezo de cebolla y tomate."},
    {id: 10, name: "Tallarines Verdes", country: "Perú", description: "Pasta bañada en salsa de albahaca y espinaca, con queso."},
    {id: 11, name: "Arroz con Mariscos", country: "Perú", description: "Arroz con una variedad de mariscos y aderezo de ají panca."},
    {id: 12, name: "Seco de Res", country: "Perú", description: "Guiso de carne de res con cilantro, servido con arroz y frijoles."},
    {id: 13, name: "Tacu Tacu", country: "Perú", description: "Mezcla de arroz y frijoles refritos, fritos en forma de tortilla."},
    {id: 14, name: "Chaufa de Pollo", country: "Perú", description: "Arroz frito al estilo chino con trozos de pollo y verduras."},
    {id: 15, name: "Juane", country: "Perú", description: "Masa de arroz con pollo, envuelta en hoja de bijao y cocida."},
    {id: 16, name: "Pollo a la Brasa", country: "Perú", description: "Pollo marinado y cocido al carbón, servido con papas fritas y ensalada."},
    {id: 17, name: "Pachamanca", country: "Perú", description: "Carne, papas y vegetales cocidos bajo tierra con piedras calientes."},
    {id: 18, name: "Caldo de Gallina", country: "Perú", description: "Sopa de pollo con fideos, papa, huevo y jengibre."},
    {id: 19, name: "Parihuela", country: "Perú", description: "Sopa de mariscos y pescado, ideal para el frío."},
    {id: 20, name: "Chifa", country: "Perú", description: "Fusión de la cocina china y peruana."},
    {id: 21, name: "Papa Rellena", country: "Perú", description: "Masa de papa rellena de carne molida y frita."},
    {id: 22, name: "Chicharrón de Pollo", country: "Perú", description: "Trozos de pollo frito y crocante."},
    {id: 23, name: "Adobo de Chancho", country: "Perú", description: "Cerdo marinado en chicha de jora y ají, cocido a fuego lento."},
    {id: 24, name: "Tiradito", country: "Perú", description: "Láminas de pescado crudo en salsa de ají y limón."},
    {id: 25, name: "Yuca Frita", country: "Perú", description: "Trozos de yuca fritos y crujientes."},

    // 25 platos de Venezuela
    {id: 26, name: "Pabellón Criollo", country: "Venezuela", description: "Arroz, carne mechada, caraotas negras y tajadas de plátano."},
    {id: 27, name: "Arepa", country: "Venezuela", description: "Masa de maíz rellena de diversos ingredientes."},
    {id: 28, name: "Reina Pepiada", country: "Venezuela", description: "Arepa rellena de una ensalada de pollo y aguacate con mayonesa."},
    {id: 29, name: "Tequeños", country: "Venezuela", description: "Dedos de queso envueltos en masa y fritos."},
    {id: 30, name: "Cachapa", country: "Venezuela", description: "Torta de maíz tierno con queso de mano."},
    {id: 31, name: "Hallaca", country: "Venezuela", description: "Masa de maíz rellena de guiso de carne, envuelta en hoja de plátano."},
    {id: 32, name: "Asado Negro", country: "Venezuela", description: "Carne de res cocida en papelón y vino tinto."},
    {id: 33, name: "Sancocho", country: "Venezuela", description: "Sopa de tubérculos y carne o pollo."},
    {id: 34, name: "Pastel de Chucho", country: "Venezuela", description: "Pastel de chucho salado con tajadas y queso."},
    {id: 35, name: "Empanada", country: "Venezuela", description: "Masa de maíz frita y rellena."},
    {id: 36, name: "Polenta", country: "Venezuela", description: "Plato de harina de maíz, similar a la polenta italiana."},
    {id: 37, name: "Hervido", country: "Venezuela", description: "Sopa o caldo hecho con verduras y carne."},
    {id: 38, name: "Mondongo", country: "Venezuela", description: "Sopa con carne de vaca y vegetales."},
    {id: 39, name: "Pisca Andina", country: "Venezuela", description: "Sopa de pollo y papa."},
    {id: 40, name: "Cachito", country: "Venezuela", description: "Pan en forma de medialuna relleno de jamón."},
    {id: 41, name: "Patacón", country: "Venezuela", description: "Plátano verde frito con ingredientes encima."},
    {id: 42, name: "Mandoca", country: "Venezuela", description: "Anillo frito de harina de maíz con queso y papelón."},
    {id: 43, name: "Golfeado", country: "Venezuela", description: "Pan dulce en forma de caracol con queso y papelón."},
    {id: 44, name: "Torta de Jojoto", country: "Venezuela", description: "Torta de maíz tierna y dulce."},
    {id: 45, name: "Arroz con Pollo", country: "Venezuela", description: "Arroz con pollo y vegetales."},
    {id: 46, name: "Chicharrón", country: "Venezuela", description: "Piel de cerdo frita y crujiente."},
    {id: 47, name: "Yuca con Mojo", country: "Venezuela", description: "Yuca cocida con una salsa de ajo y limón."},
    {id: 48, name: "Quesillo", country: "Venezuela", description: "Postre similar al flan."},
    {id: 49, name: "Tizana", country: "Venezuela", description: "Bebida de frutas picadas y jugo."},
    {id: 50, name: "Ensalada de Gallina", country: "Venezuela", description: "Ensalada de pollo desmenuzado, papa y zanahoria con mayonesa."},
];